### ISSUE TITLE
Regra conflitua com o i18n

### ISSUE THREAD

**Issue by mkny** [SoftboxLab/gandalf-lint#10]
A regra abaixo está conflituando com o `react-i18next`.
Ele possui um HOC que injeta uma propriedade chamada `t()`. E com isso, a linha dá erro no id-length do eslint.

https://github.com/SoftboxLab/gandalf-lint/blob/26d391e89fc553fbbb0394b094a33058d353c583/rules/gandalf.js#L327

**Comment by pablohpsilva** [comment]
Ola @mkny 
Vou dar uma olhada nisso hoje ainda. Obrigado :)

**Comment by vilaboim** [comment]
@pablohpsilva essa regra poderia ser colocada no gandalf-lint-react, o que acha?

**Comment by pablohpsilva** [comment]
Eu nao acho que podemos colocar @vilaboim, porque quem esta usando o `gandalf-lint-react` vai ter o mesmo problema :(
Talvez podemos ignorar para algumas libs, de alguma forma

**Comment by vilaboim** [comment]
@pablohpsilva, me expressei mal, quis dizer para remover essa regra no gandalf-lint-react, por saber que muitos plugins e libraries que usam props vão ter esse problema.

Aí aqui no gandalf-lint ela continuaria.

**Comment by pablohpsilva** [comment]
Acho melhor assim :)
@mkny voce esta usando o gandalf-lint somente ou em conjunto com o gandalf-react?

**Comment by mkny** [comment]
@pablohpsilva Somente o gandalf-lint. O gandalf-react tá com umas inconsistencias, segundo o vila

**Comment by pablohpsilva** [comment]
@vilaboim eu modifiquei a regra pra mandar um `warning` por enquanto aqui no gandalf-lint.

**Comment by vilaboim** [comment]
@pablohpsilva não acha esse um problema muito específico para modificarmos uma regra?
O PR que você fez no gandalf-lint-react já não resolve?

**Comment by pablohpsilva** [comment]
@vilaboim  Eu concordo com voce, mas dai voces continuarao com erros hahahahaha...

**Comment by vilaboim** [comment]
@pablohpsilva hahaha, mas colocamos uma regra direto no projeto.
Eu mesclei seu PR no gandalf-react, então logo poderemos usá-lo.
