### ISSUE TITLE
Please clarify license for this repo

### ISSUE THREAD

**Issue by rturk** [SoftboxLab/gandalf-lint#2]
Hi SofBoxLab team, this is a great code, thats for sharing.

Can you please clarify license for this repo? Hopefully MIT?

**Comment by pablohpsilva** [comment]
Hello @rturk thanks for reaching out.

We're building this linting rules and there are a few things missing. We extended the eslint-config-standard, got some ideas/rules from eslint-config-airbnb-base and also some ideas from TSlint itself to create gandalf-lint.

I've added both the airbnb and standard MIT's license on the README of this repo. Consequently this project is also MIT licensed. I'll add the LICENSE.md soon enough.

Would you like to contribute on this project? We would be much obliged on having your help :)
