### ISSUE TITLE
Regras eslint para retornar / adicionar

### ISSUE THREAD

**Issue by mkny** [SoftboxLab/gandalf-lint#22]
- `"max-params": ["error", 3],`
Limita o máximo de parâmetros na função, forçando funções que tiverem mais parâmetros a serem tratadas como objects.

- Voltar com o `"comma-dangle": [ "error", "always-multiline" ],`

**Comment by vilaboim** [comment]
@mkny, como as regras falam de coisas diferentes, crie uma issue para cada item, por favor.
E fica mais fácil de rastrear quando chegarem os PRs.
