### ISSUE TITLE
Documentação das regras utilizadas

### ISSUE THREAD

**Issue by vilaboim** [SoftboxLab/gandalf-lint#9]
No projeto [Juggernaut](https://github.com/SoftboxLab/juggernaut) nós sentimos a falta de uma documentação com as regras que são utilizadas no gandalf-lint, para decidirmos se ele realmente funcionaria para nós.

É possível criar uma documentação assim?

**Comment by victormaestri** [comment]
@vila iremos estudar a possibilidade de redefinir as regras aplicadas no gandalf lint. Feito isso faremos uma documentação com as regras aplicadas
